// Copyright (c) 2026 Test Synthesis Framework
// Licensed under the MIT License

using System.Text.Json.Serialization;

namespace ReverseCoverage.TargetModel.Models;

/// <summary>
/// Represents a test case specification generated by the AI plugin.
/// </summary>
public class TestCaseSpec
{
    [JsonPropertyName("testName")]
    public string TestName { get; set; } = string.Empty;

    [JsonPropertyName("targetMethodId")]
    public string TargetMethodId { get; set; } = string.Empty;

    [JsonPropertyName("arrange")]
    public StepSpec[] Arrange { get; set; } = Array.Empty<StepSpec>();

    [JsonPropertyName("act")]
    public StepSpec Act { get; set; } = new();

    [JsonPropertyName("assert")]
    public AssertionSpec[] Assert { get; set; } = Array.Empty<AssertionSpec>();

    [JsonPropertyName("expectedProbeImpact")]
    public string[] ExpectedProbeImpact { get; set; } = Array.Empty<string>(); // probe ids or human tags

    [JsonPropertyName("tags")]
    public string[] Tags { get; set; } = Array.Empty<string>();
}

